version: '0.0.1'
services:
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
  api1:
    image: api-server-image
    stop_grace_period: 1s
  api2:
    image: api-server-image
    stop_grace_period: 1s
  minio:
    image: minio/minio
    volumes:
      - ./minio/.data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
  postgresql:
    image: postgres:16-alpine
    volumes:
      - ./postgres/.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379