version: '0.0.1'
services:
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
  api1:
    image: api-server-image
  api2:
    image: api-server-image